# -*- coding: utf-8 -*-

LANGS = {
    "zh": "中文",
    "en": "English"
}

I18N = {
    "zh": {
        "nav_platform": "平台",
        "nav_role": "身份切换",
        "nav_lang": "语言",
        "nav_timezone": "时区",
        "nav_tenant": "租户",
        "nav_sys_info": "系统信息",
        "nav_help": "帮助",
        "nav_docs_arch": "系统架构文档",
        "nav_docs_kb": "知识库用户手册",
        
        "plat_knowledge": "知识库",
        "plat_knowledge_desc": "知识库配置与检索",
        "plat_audit": "审核配置",
        "plat_audit_desc": "关键词与日志管理",
        "plat_business": "商业化运营",
        "plat_business_desc": "订阅/计费/数据看板",
        "plat_telegram": "Telegram",
        "plat_telegram_desc": "全功能支持 - 私聊/群聊/频道",
        "plat_whatsapp": "WhatsApp",
        "plat_whatsapp_desc": "可用 - 私聊/群聊自动回复",
        "plat_accounts": "账号管理",
        "plat_accounts_desc": "集中录入与分组/标签管理",
        "plat_ai_config": "AGNT AI配置中心",
        "plat_ai_config_desc": "AI服务商接入与A/B测试",
        "plat_api_gateway": "API接口管理中心",
        "plat_api_gateway_desc": "统一网关/权限/流控/日志",
        "plat_sys_config": "系统配置自动化",
        "plat_sys_config_desc": "环境/会话/密钥自动化",
        
        "bus_header": "商业化运营中心",
        "bus_tab_dashboard": "数据看板",
        "bus_tab_sub": "订阅管理",
        "bus_tab_brand": "品牌定制",
        "bus_metrics_core": "核心指标",
        "bus_active_users": "今日活跃用户",
        "bus_api_calls": "API调用量",
        "bus_funnel": "转化漏斗",
        "bus_revenue": "本月预估营收",
        "bus_total_tokens": "总 Token 消耗",
        "bus_total_cost": "总成本估算 ($)",
        "bus_cost_breakdown": "成本分布 (按 Stage)",
        "bus_trend": "趋势分析",
        "bus_sub_plan": "订阅方案",
        "bus_current_plan": "当前方案",
        "bus_expiry": "到期时间",
        "bus_brand_title": "品牌定制 (White Label)",
        "bus_brand_warn": "此功能仅限 Pro/Enterprise 用户使用",
        "bus_company_name": "公司名称",
        "bus_theme_color": "主题色",
        "bus_save_brand": "保存品牌设置",
        "bus_save_success": "设置已保存",
        
        "bus_plan_free_title": "免费版 (Free)",
        "bus_plan_free_feat1": "- 1 个机器人实例",
        "bus_plan_free_feat2": "- 每日 100 条消息",
        "bus_plan_free_btn": "降级/选择",
        
        "bus_plan_pro_title": "专业版 ($99/月)",
        "bus_plan_pro_feat1": "- 5 个机器人实例",
        "bus_plan_pro_feat2": "- 每日 5,000 条消息",
        "bus_plan_pro_feat3": "- 数据分析看板",
        "bus_plan_pro_btn": "升级到专业版",
        
        "bus_plan_ent_title": "企业版 ($999/月)",
        "bus_plan_ent_feat1": "- 无限机器人",
        "bus_plan_ent_feat2": "- 品牌定制 (White Label)",
        "bus_plan_ent_feat3": "- 专属技术支持",
        "bus_plan_ent_btn": "联系销售",
        
        "common_select": "选择",
        "common_selected": "✓",
        "common_save": "保存",
        "common_success": "成功",
        "common_error": "错误",
        "common_edit": "编辑",
        "common_delete": "删除",
        "common_cancel": "取消",
        "common_confirm": "确认",
        "common_back": "返回",
        "common_next": "下一步",
        "common_finish": "完成",

        "kb_header": "知识库配置与管理",
        "kb_tab_manage": "管理",
        "kb_tab_import": "导入",
        "kb_tab_test": "检索测试",
        "kb_tab_settings": "设置",
        "kb_list_title": "知识条目列表",
        "kb_no_items": "暂无条目，可在“导入”或下方创建。",
        "kb_col_title": "标题",
        "kb_col_category": "分类",
        "kb_col_tags": "标签",
        "kb_col_source": "来源文件",
        "kb_col_action": "操作",
        "kb_new_item": "新建文本条目",
        "kb_input_title": "标题",
        "kb_input_cat": "分类",
        "kb_input_tags": "标签（逗号分隔）",
        "kb_input_content": "内容",
        "kb_btn_save": "保存条目",
        "kb_err_empty": "请输入标题或内容",
        "kb_edit_title": "编辑条目",
        "kb_import_header": "导入文件",
        "kb_import_desc": "选择文件（支持 txt/md/pdf/docx/xlsx）",
        "kb_import_preview": "内容预览（可编辑）",
        "kb_import_save": "保存为条目",
        "kb_test_header": "检索测试",
        "kb_test_input": "输入检索关键词或问题",
        "kb_test_topn": "返回条数",
        "kb_test_btn": "执行检索",
        "kb_settings_header": "设置与依赖",

        "tg_header": "Telegram AI Bot 控制面板",
        "tg_status_running": "🟢 运行中",
        "tg_status_stopped": "🔴 已停止",
        "tg_status_logged_in": "✅ 已登录",
        "tg_status_not_logged_in": "⚠️ 未登录",
        "tg_btn_login": "未登录 Telegram（点击登录）",

        "tg_tab_config": "🧠 配置",
        "tg_tab_broadcast": "📢 群发",
        "tg_tab_logs": "📜 日志",
        "tg_tab_stats": "📊 统计",
        "tg_tab_flow": "🧭 时序图",

        "tg_config_header": "⚙️ 配置管理",
        "tg_cfg_persona": "**AI 人设**",
        "tg_cfg_prompt_label": "编辑提示词",
        "tg_cfg_save_prompt": "💾 保存人设",
        "tg_cfg_keywords": "**触发关键词**",
        "tg_cfg_keywords_placeholder": "每行一个",
        "tg_cfg_save_keywords": "💾 保存关键词",
        "tg_cfg_qa": "**QA问题库**",
        "tg_cfg_qa_placeholder": "QA问题库（支持 Q:/A: 或 question||answer）",
        "tg_cfg_save_qa": "💾 保存QA",
        "tg_cfg_switches": "**功能开关**",
        "tg_cfg_private_reply": "私聊自动回复",
        "tg_cfg_group_reply": "群聊自动回复",
        "tg_cfg_quote": "**引用设置**",
        "tg_cfg_auto_quote": "自动引用",
        "tg_cfg_quote_interval": "引用时间间隔(秒)",
        "tg_cfg_quote_len": "引用内容长度(字符)",
        "tg_cfg_temp": "**🌡️ AI 创造性 (Temperature)**",
        "tg_cfg_temp_label": "调整 AI 回复的随机性与创造性",
        "tg_cfg_audit": "**🛡️ 内容审核系统 (双机拦截)**",
        "tg_cfg_audit_enable": "启用审核员 AI",
        "tg_cfg_audit_mode": "审核模式",
        "tg_cfg_audit_retries": "最大重试次数",
        "tg_cfg_audit_strictness": "审核员严格度",
        "tg_cfg_audit_guide": "合规引导强度",
        "tg_cfg_audit_temp_off": "⏸️ 临时关闭审核（5分钟）",
        "tg_cfg_audit_restore": "▶️ 立即恢复审核配置",
        "tg_cfg_audit_servers": "远程审核服务器地址 (多个用逗号分隔)",
        "tg_cfg_save_all": "💾 保存配置",
        "tg_cfg_audit_kw": "**🔒 审核员关键词配置（双机拦截）**",
        "tg_cfg_conv_mode": "对话呈现模式",
        "tg_cfg_conv_ai": "官方客服 / 技术支持",
        "tg_cfg_conv_human": "模拟真人沟通",
        "tg_kw_block": "违禁词",
        "tg_kw_sensitive": "敏感词",
        "tg_kw_allow": "允许词（品牌设定白名单）",
        "tg_kw_add": "添加",
        "tg_kw_del": "删除选中",
        "tg_kw_rename": "重命名",
        "tg_kw_new_name": "新名称",
        "tg_kw_fallback": "**📝 审核员兜底话术库（每行一条）**",
        "tg_kw_save_fallback": "💾 保存兜底话术",
        "tg_kw_clean_qa": "**🧹 QA 知识库清理**",
        "tg_kw_clean_btn": "🔎 扫描并清理不合规条目",
        "tg_whitelist_header": "📌 群白名单",
        "tg_whitelist_select": "选择允许自动回复的群组",
        "tg_whitelist_save": "💾 保存白名单",

        "tg_bc_header": "📢 群发",
        "tg_bc_warn": "⚠️ 频繁群发可能导致账号被限制，建议小批量测试。",
        "tg_bc_mode": "群组加载方式",
        "tg_bc_mode_whitelist": "白名单群组",
        "tg_bc_mode_non_whitelist": "非白名单群组",
        "tg_bc_mode_all": "全部群组",
        "tg_bc_load_btn": "加载群组",
        "tg_bc_select_all": "全选",
        "tg_bc_select_none": "全不选",
        "tg_bc_select_invert": "反选",
        "tg_bc_select_label": "选择群组",
        "tg_bc_interval": "群发间隔（秒）",
        "tg_bc_msg_placeholder": "输入要群发的消息...",
        "tg_bc_send_btn": "🚀 开始群发",
        "tg_bc_records": "📋 群发记录",
        "tg_bc_clear": "清空记录",
        "tg_bc_no_cache": "⚠️ 未找到群组缓存",
        "tg_bc_fail_prefix": "❌ 群发失败: {}",
        "tg_bc_success_fmt": "✅ 群发完成: 成功 {}, 失败 {}",

        "tg_log_header": "📜 运行日志",
        "tg_log_sys": "系统日志",
        "tg_log_priv": "私聊日志",
        "tg_log_grp": "群聊日志",
        "tg_log_audit": "审核日志",
        "tg_log_load": "加载日志",
        "tg_log_refresh": "刷新",
        "tg_log_clear": "清空日志",

        "tg_flow_header": "🧭 客户到 AI 回复时序",
        "tg_btn_start": "🚀 启动机器人",
        "tg_btn_stop": "⛔ 停止机器人",
        "tg_btn_restart": "🔄 重启机器人",
        "tg_restart_success": "机器人已重启",
        "tg_login_header": "Telegram 登录",
        "tg_login_success": "✅ 已登录",
        "tg_login_warning": "⚠️ 未登录",
        "tg_login_btn": "未登录 Telegram（点击登录）",
        "tg_config_success": "✅ 已配置",
        "tg_config_missing": "❌ 未配置",
        "tg_panel_header": "Telegram AI Bot 控制面板",
        "tg_flow_entry": "**1. 消息接入 (Ingest)**：用户发送消息 → Telethon 监听事件 → 权限与意图识别",
        "tg_flow_trigger": "**2. 核心路由 (Routing)**：判断消息类型 (私聊/群聊) 与 触发条件 (关键词/白名单)",
        "tg_flow_branch_a": "**3A. 快速响应 (QA/Fast Path)**",
        "tg_flow_branch_a_1": "- 匹配 `qa.txt` 固定问答库",
        "tg_flow_branch_a_2": "- 命中则直接返回预设答案",
        "tg_flow_branch_a_3": "- 记录基础日志",
        "tg_flow_branch_b": "**3B. 智能生成 (AI/RAG Path)**",
        "tg_flow_branch_b_1": "- **检索**: 查询知识库 (KBEngine) 获取 Top-K 上下文",
        "tg_flow_branch_b_2": "- **生成**: 构建 Prompt (System+KB+History) 调用 LLM",
        "tg_flow_branch_b_3": "- **审计**: AuditManager 双重风控 (本地规则 + AI 审核)",
        "tg_flow_branch_b_4": "- **决策**: 审核通过 -> 发送回复；审核拒绝 -> 触发兜底/重试",
        "tg_flow_branch_b_5": "- **反馈**: 记录完整交互日志 (User/Bot/Audit/Token)",
        "tg_flow_branch_b_6": "",
        "tg_flow_kw_prio": "**4. 安全防护 (Security)**",
        "tg_flow_kw_prio_1": "- allow：命中直接允许",
        "tg_flow_kw_prio_2": "- block：命中直接拒绝，触发兜底",
        "tg_flow_kw_prio_3": "- sensitive：记录并拒绝（可调整为警告）",
        "tg_flow_fallback": "**兜底话术**",
        "tg_flow_fallback_1": "- 来源：platforms/telegram/audit_fallback.txt",
        "tg_flow_fallback_2": "- 可在配置页直接编辑并保存",
        "tg_flow_files": "**文件与模块**",
        "tg_flow_files_1": "- 处理主链路：[main.py](file:///d:/AI%20Talk/main.py)",
        "tg_flow_files_2": "- 审核与兜底：[audit_manager.py](file:///d:/AI%20Talk/audit_manager.py)",
        "tg_flow_files_3": "- 关键词管理：[keyword_manager.py](file:///d:/AI%20Talk/keyword_manager.py)",
        "tg_flow_files_4": "- 配置后台：[admin_multi.py](file:///d:/AI%20Talk/admin_multi.py)",
        "tg_stats_total_users": "总用户数",
        "tg_stats_active_today": "今日活跃",
        "tg_stats_total_msgs": "总消息数",
        "tg_stats_trend_7d": "近7日趋势",
        "tg_stats_title": "使用统计",
        "tg_stats_total_replies": "总回复数",
        "tg_stats_success_rate": "成功率",
        "tg_stats_fail_count": "失败次数",
        "tg_stats_private": "私聊消息",
        "tg_stats_group": "群聊消息",
        "tg_stats_uptime_fmt": "⏱️ 运行时长: {d}天 {h}小时 {m}分钟",
        "tg_stats_last_active": "最后活跃: {}",
        "tg_stats_audit_trend": "审核与兜底趋势",
        "tg_stats_audit_desc": "统计最近 1000 行审核日志中的 PASS/FAIL/兜底触发次数",
        "tg_stats_chart_cat": "类别",
        "tg_stats_chart_count": "次数",
        "tg_stats_chart_fallback": "兜底",
        "tg_stats_reset": "🗑️ 重置统计",
        "tg_stats_reset_success": "✅ 统计已重置",
        "tg_stats_read_fail": "读取统计失败: {}",
        "tg_stats_tip_wait": "💡 统计数据将在机器人运行后生成",
        "wa_header": "WhatsApp 自动回复机器人",
        "wa_qr_title": "WhatsApp 登录二维码",
        "wa_qr_scan_hint": "请使用手机 WhatsApp 扫描下方二维码登录",
        "wa_qr_caption": "扫描此二维码登录",
        "wa_qr_step1": "提示：打开 WhatsApp > 设置 > 已连接的设备 > 连接设备",
        "wa_qr_step2": "⏳ 二维码有效期约 20 秒，过期请重启机器人",
        "wa_qr_refresh": "🔄 刷新查看状态",
        "wa_status_read_err": "读取登录状态失败: {}",
        "wa_btn_start": "🚀 启动机器人",
        "wa_btn_stop": "⛔ 停止机器人",
        "wa_btn_restart": "🔄 重启机器人",
        "wa_restart_success": "机器人已重启",
        "wa_log_header": "📜 运行日志",
        "wa_log_refresh": "🔄 刷新日志",
        "wa_log_empty": "📝 日志为空，等待机器人产生输出...",
        "wa_log_missing": "⚠️ 日志文件不存在，请先启动机器人",
        "wa_log_clear": "🗑️ 清空日志",
        "wa_log_cleared": "✅ 日志已清空",
        "wa_stats_header": "📊 使用统计",
        "wa_stats_reset": "🗑️ 重置统计",
        "wa_stats_reset_success": "✅ 统计已重置",
        "wa_cfg_header": "⚙️ 配置管理",
        "wa_cfg_persona": "AI 人设",
        "wa_cfg_prompt_label": "编辑提示词",
        "wa_cfg_save_prompt": "💾 保存人设",
        "wa_cfg_keywords": "触发关键词",
        "wa_cfg_keywords_label": "群聊关键词（每行一个）",
        "wa_cfg_save_keywords": "💾 保存关键词",
        "wa_cfg_switches": "功能开关",
        "wa_cfg_private_reply": "私聊回复",
        "wa_cfg_group_reply": "群聊回复",
        "wa_cfg_save_config": "💾 保存开关配置",
        "wa_cfg_tip_restart": "💡 修改后立即生效，无需重启机器人",
        "wa_log_file_size": "📁 文件大小: {} 字节",
        "wa_log_last_updated": "📅 最后更新: {}",
        "wa_log_read_err": "❌ 读取日志失败: {}",
        "wa_log_clear_fail": "❌ 清空失败",
        "wa_stats_total_msgs": "总消息数",
        "wa_stats_total_replies": "总回复数",
        "wa_stats_success_rate": "成功率",
        "wa_stats_failures": "失败次数",
        "wa_stats_private": "私聊消息",
        "wa_stats_group": "群聊消息",
        "wa_stats_runtime": "⏱️ 运行时长: {d}天 {h}小时 {m}分钟",
        "wa_stats_last_active": "最后活跃: {}",
        "wa_stats_read_err": "读取统计失败: {}",
        "wa_stats_wait": "💡 统计数据将在机器人运行后生成",
        
        "orch_header": "AI剧本配置 Orchestrator",
        "orch_tab_stage": "Stage 管理",
        "orch_tab_persona": "Persona 管理",
        "orch_tab_binding": "绑定关系",
        "orch_stage_name": "Stage 名称",
        "orch_stage_version": "版本",
        "orch_stage_content": "内容(JSON)",
        "orch_btn_save_stage": "保存 Stage",
        "orch_persona_name": "Persona 名称",
        "orch_persona_version": "版本",
        "orch_persona_content": "内容(JSON)",
        "orch_btn_save_persona": "保存 Persona",
        "orch_binding_content": "Stage×Persona→AgentProfile 映射(JSON)",
        "orch_btn_save_binding": "保存绑定",
        "orch_save_success": "✅ 已保存",
        "sup_header": "Supervisor 监控台",
        "sup_list_title": "当前会话列表",
        "sup_select_user": "选择会话",
        "sup_force_stage": "强制 Stage",
        "sup_force_persona": "强制 Persona",
        "sup_handoff": "人工接管",
        "sup_btn_apply": "应用",
        "sup_apply_success": "✅ 已应用",
        "sup_route_title": "最近路由决策",
        "sup_route_col_user": "用户",
        "sup_route_col_platform": "平台",
        "sup_route_col_time": "时间",
        "sup_route_col_decision": "决策",
        
        "common_coming_soon": "{} - 开发中",
        "common_in_dev": "### 🚧 平台开发中",
        "common_planned_features": "**计划功能：**",
        "common_contact_dev": "💡 如果你急需此平台支持，请联系开发者。",
        "common_dev_progress": "### 📈 开发进度",
        "common_progress_fmt": "完成度: {}%",
        
        "audit_header": "🛡️ 审核员配置中心",
        "audit_role_warn": "仅审核员可访问此模块。请在左侧切换身份为 Auditor。",
        "audit_tab_keywords": "关键词管理",
        "audit_tab_logs": "审核日志",
        "audit_tab_config": "配置",
        "audit_cfg_enable": "启用审核系统",
        "audit_cfg_remote": "使用远程审核服务",
        "audit_cfg_url": "远程服务地址",
        "audit_cfg_remote_help": "多个地址用逗号分隔，优先使用第一个",
        "audit_cfg_key": "API 密钥",
        "audit_cfg_save": "保存配置",
        "audit_log_col_time": "时间",
        "audit_log_col_role": "角色",
        "audit_log_col_action": "动作",
        "audit_log_col_details": "详情",
        "audit_log_no_data": "暂无日志",
        "audit_kw_info": "此处配置的关键词将实时生效，用于拦截或标记敏感内容。",
        "audit_block_header": "#### 🚫 违禁词 (Block)",
        "audit_block_caption": "触发此类关键词将直接拦截回复",
        "audit_block_count": "当前共 {} 个违禁词",
        "audit_block_add": "添加违禁词",
        "audit_block_add_btn": "添加",
        "audit_block_del_sel": "选择要删除的违禁词",
        "audit_block_del_btn": "删除选中",
        "audit_block_rename_sel": "选择重命名的违禁词",
        "audit_block_rename_new": "新的名称",
        "audit_block_rename_btn": "重命名",
        "audit_sens_header": "#### ⚠️ 敏感词 (Sensitive)",
        "audit_sens_caption": "触发此类关键词将记录日志并拒绝（或警告）",
        "audit_sens_count": "当前共 {} 个敏感词",
        "audit_sens_add": "添加敏感词",
        "audit_sens_del_sel": "选择要删除的敏感词",
        "audit_sens_rename_sel": "选择重命名的敏感词",
        "audit_allow_header": "#### ✅ 允许词（品牌设定白名单）",
        "audit_allow_count": "当前共 {} 个允许词",
        "audit_allow_add": "添加允许词",
        "audit_allow_del_sel": "选择要删除的允许词",
        "audit_allow_rename_sel": "选择重命名的允许词",
        "audit_log_recent": "最近审核日志",
        "audit_log_refresh": "刷新日志",
        
        "api_header": "API接口管理中心",
        "api_route_path": "接口路径 /audit /reply",
        "api_route_method": "方法",
        "api_route_auth": "鉴权",
        "api_route_rate": "流量限制 req/min",
        "api_btn_add": "添加/更新路由",
        "api_save_success": "✅ 已保存路由",
        "api_list_header": "路由列表",

        "sys_header": "系统配置自动化",
        "sys_env_header": "环境配置 (env)",
        "sys_status": "状态",
        "sys_status_gen": "已生成",
        "sys_status_not_gen": "未生成",
        "sys_file_path": "文件: {}",
        "sys_btn_gen_env": "一键生成/更新 .env",
        "sys_success_env": "✅ .env 已生成/更新",
        "sys_session_header": "会话文件生成",
        "sys_btn_init_session": "静默初始化会话文件",
        "sys_success_session": "✅ 会话文件已初始化",
        "sys_secret_header": "敏感信息加密与查看",
        "sys_secret_caption": "默认显示为掩码；查看需二次验证并记录审计日志",
        "sys_btn_gen_code": "生成二次验证码",
        "sys_code_info": "已生成，请输入验证码进行查看",
        "sys_input_code": "输入验证码以查看",
        "sys_btn_view": "查看明文",
        "sys_success_view": "✅ 验证通过（当前会话有效）",
        "sys_err_code": "验证码不正确",
        
        "acc_header": "账号管理",
        "acc_tenant": "当前租户: {}",
        "acc_subtitle": "平台/账号集中录入与分组、标签管理",
        "acc_col_platform": "平台",
        "acc_col_username": "账号名/ID",
        "acc_col_group": "分组",
        "acc_col_tags": "标签（逗号分隔）",
        "acc_col_refresh": "刷新间隔（分钟）",
        "acc_btn_add": "添加/更新账号",
        
        "cs_title": "🚧 平台开发中",
        "cs_desc": "**{}** 功能正在开发中，敬请期待！",
        "cs_plan_title": "**计划功能：**",
        "cs_plan_1": "✅ 自动回复",
        "cs_plan_2": "✅ 上下文记忆",
        "cs_plan_3": "✅ 群发消息",
        "cs_plan_4": "✅ Web 管理",
        "cs_plan_5": "✅ 统计报表",
        "cs_eta": "**预计上线：** 待定",
        "cs_contact": "💡 如果你急需此平台支持，请联系开发者。",
        "cs_progress_title": "### 📈 开发进度",
        "cs_progress_caption": "完成度: {}%",
        
        "wa_status_running": "🟢 运行中",
        "wa_status_stopped": "🔴 已停止",
        "wa_start_success": "✅ WhatsApp 机器人已启动 (PID: {})",
        "wa_start_fail": "❌ 启动失败: {}",
        "wa_err_no_node": "❌ 未检测到 Node.js，请先安装",
        "wa_err_missing_deps": "❌ 依赖缺失，请先运行 install.bat/ install.sh",
        "wa_stop_success": "✅ WhatsApp 机器人已停止",
        "wa_stop_not_running": "⚠️ 机器人未运行",
        "wa_stop_fail": "❌ 停止失败: {}",
        "audit_db_err": "无法从数据库加载日志: {}",
        "audit_save_err": "保存配置失败: {}",
        "acc_save_success": "✅ 已保存账号",
        "acc_list_title": "账号列表",
        "ai_subtitle": "可视化配置AI服务商、模型版本与A/B权重",
        "ai_provider": "服务商",
        "ai_base_url": "Base URL",
        "ai_model": "模型版本",
        "ai_weight": "A/B权重",
        "ai_api_key": "API Key（不落盘展示）",
        "ai_timeout": "请求超时（秒）",
        "tg_bc_logs_label": "日志",
        "tg_bc_exec_err": "执行错误: {}",
    },
    "en": {
        "nav_platform": "Platform",
        "nav_role": "Role Switch",
        "nav_lang": "Language",
        "nav_timezone": "Timezone",
        "nav_tenant": "Tenant",
        "nav_sys_info": "System Info",
        "nav_help": "Help",
        "nav_docs_arch": "System Architecture",
        "nav_docs_kb": "KB User Guide",
        
        "plat_knowledge": "Knowledge Base",
        "plat_knowledge_desc": "KB Config & Retrieval",
        "plat_audit": "Audit Config",
        "plat_audit_desc": "Keywords & Logs",
        "plat_business": "Business Ops",
        "plat_business_desc": "Sub/Billing/Dashboard",
        "plat_telegram": "Telegram",
        "plat_telegram_desc": "Full Support - DM/Group/Channel",
        "plat_whatsapp": "WhatsApp",
        "plat_whatsapp_desc": "Available - DM/Group Auto-reply",
        "plat_accounts": "Accounts",
        "plat_accounts_desc": "Centralized Accounts & Tags",
        "plat_ai_config": "AGNT AI Config",
        "plat_ai_config_desc": "AI Providers & A/B Testing",
        "plat_api_gateway": "API Gateway",
        "plat_api_gateway_desc": "Gateway/Auth/RateLimit/Logs",
        "plat_sys_config": "System Config",
        "plat_sys_config_desc": "Env/Session/Keys Auto",
        
        "bus_header": "Business Operations Center",
        "bus_tab_dashboard": "Dashboard",
        "bus_tab_sub": "Subscription",
        "bus_tab_brand": "Branding",
        "bus_metrics_core": "Core Metrics",
        "bus_active_users": "Active Users (Today)",
        "bus_api_calls": "API Calls",
        "bus_funnel": "Conversion Funnel",
        "bus_revenue": "Est. Revenue (Mo)",
        "bus_total_tokens": "Total Tokens",
        "bus_total_cost": "Total Cost ($)",
        "bus_cost_breakdown": "Cost Breakdown (by Stage)",
        "bus_trend": "Trend Analysis",
        "bus_sub_plan": "Subscription Plans",
        "bus_current_plan": "Current Plan",
        "bus_expiry": "Expires At",
        "bus_brand_title": "White Label Branding",
        "bus_brand_warn": "Feature available for Pro/Enterprise only",
        "bus_company_name": "Company Name",
        "bus_theme_color": "Theme Color",
        "bus_save_brand": "Save Branding",
        "bus_save_success": "Settings Saved",
        
        "bus_plan_free_title": "Free Plan",
        "bus_plan_free_feat1": "- 1 Bot Instance",
        "bus_plan_free_feat2": "- 100 Daily Msgs",
        "bus_plan_free_btn": "Downgrade/Select",
        
        "bus_plan_pro_title": "Pro Plan ($99/mo)",
        "bus_plan_pro_feat1": "- 5 Bot Instances",
        "bus_plan_pro_feat2": "- 5,000 Daily Msgs",
        "bus_plan_pro_feat3": "- Analytics Dashboard",
        "bus_plan_pro_btn": "Upgrade to Pro",
        
        "bus_plan_ent_title": "Enterprise ($999/mo)",
        "bus_plan_ent_feat1": "- Unlimited Bots",
        "bus_plan_ent_feat2": "- White Labeling",
        "bus_plan_ent_feat3": "- Dedicated Support",
        "bus_plan_ent_btn": "Contact Sales",
        
        "common_select": "Select",
        "common_selected": "✓",
        "common_save": "Save",
        "common_success": "Success",
        "common_error": "Error",
        "common_edit": "Edit",
        "common_delete": "Delete",
        "common_cancel": "Cancel",
        "common_confirm": "Confirm",
        "common_back": "Back",
        "common_next": "Next",
        "common_finish": "Finish",

        "kb_header": "Knowledge Base Management",
        "kb_tab_manage": "Manage",
        "kb_tab_import": "Import",
        "kb_tab_test": "Test",
        "kb_tab_settings": "Settings",
        "kb_list_title": "Knowledge Items",
        "kb_no_items": "No items found. Create below or Import.",
        "kb_col_title": "Title",
        "kb_col_category": "Category",
        "kb_col_tags": "Tags",
        "kb_col_source": "Source File",
        "kb_col_action": "Action",
        "kb_new_item": "New Text Item",
        "kb_input_title": "Title",
        "kb_input_cat": "Category",
        "kb_input_tags": "Tags (comma separated)",
        "kb_input_content": "Content",
        "kb_btn_save": "Save Item",
        "kb_err_empty": "Title or Content required",
        "kb_edit_title": "Edit Item",
        "kb_import_header": "Import Files",
        "kb_import_desc": "Upload Files (txt/md/pdf/docx/xlsx)",
        "kb_import_preview": "Content Preview (Editable)",
        "kb_import_save": "Save as Item",
        "kb_test_header": "Retrieval Test",
        "kb_test_input": "Enter keywords or question",
        "kb_test_topn": "Top N",
        "kb_test_btn": "Search",
        "kb_settings_header": "Settings & Dependencies",

        "tg_header": "Telegram AI Bot Control Panel",
        "tg_status_running": "🟢 Running",
        "tg_status_stopped": "🔴 Stopped",
        "tg_status_logged_in": "✅ Logged In",
        "tg_status_not_logged_in": "⚠️ Not Logged In",
        "tg_btn_login": "Login to Telegram",
        
        "tg_tab_config": "Config",
        "tg_tab_broadcast": "Broadcast",
        "tg_tab_logs": "Logs",
        "tg_tab_stats": "Stats",
        "tg_tab_flow": "Flow",

        "tg_config_header": "Config Management",
        "tg_cfg_persona": "AI Persona",
        "tg_cfg_prompt_label": "Edit Prompt",
        "tg_cfg_save_prompt": "Save Persona",
        "tg_cfg_keywords": "Keywords",
        "tg_cfg_keywords_placeholder": "One per line",
        "tg_cfg_save_keywords": "Save Keywords",
        "tg_cfg_qa": "QA Knowledge Base",
        "tg_cfg_qa_placeholder": "QA DB (Supports Q:/A: or question||answer)",
        "tg_cfg_save_qa": "Save QA",
        "tg_cfg_switches": "Feature Switches",
        "tg_cfg_private_reply": "Private Auto-Reply",
        "tg_cfg_group_reply": "Group Auto-Reply",
        "tg_cfg_quote": "Quote Settings",
        "tg_cfg_auto_quote": "Auto Quote",
        "tg_cfg_quote_interval": "Quote Interval (s)",
        "tg_cfg_quote_len": "Quote Max Length",
        "tg_cfg_temp": "AI Temperature",
        "tg_cfg_temp_label": "Adjust AI creativity/randomness",
        "tg_cfg_audit": "Content Audit System",
        "tg_cfg_audit_enable": "Enable Audit AI",
        "tg_cfg_audit_mode": "Audit Mode",
        "tg_cfg_audit_retries": "Max Retries",
        "tg_cfg_audit_strictness": "Audit Strictness",
        "tg_cfg_audit_guide": "Guide Strength",
        "tg_cfg_audit_temp_off": "Pause Audit (5min)",
        "tg_cfg_audit_restore": "Restore Audit Config",
        "tg_cfg_audit_servers": "Remote Audit Servers (comma separated)",
        "tg_cfg_save_all": "Save Config",
        "tg_cfg_audit_kw": "Auditor Keywords Config",
        "tg_cfg_conv_mode": "Conversation Mode",
        "tg_cfg_conv_ai": "AI Visible (Official Support)",
        "tg_cfg_conv_human": "Human Simulated",
        "tg_kw_block": "Blocklist",
        "tg_kw_sensitive": "Sensitive",
        "tg_kw_allow": "Allowlist",
        "tg_kw_add": "Add",
        "tg_kw_del": "Delete Selected",
        "tg_kw_rename": "Rename",
        "tg_kw_new_name": "New Name",
        "tg_kw_fallback": "Audit Fallback Responses",
        "tg_kw_save_fallback": "Save Fallback",
        "tg_kw_clean_qa": "Clean QA DB",
        "tg_kw_clean_btn": "Scan & Clean Invalid Items",
        "tg_whitelist_header": "Group Whitelist",
        "tg_whitelist_select": "Select Whitelisted Groups",
        "tg_whitelist_save": "Save Whitelist",

        "tg_bc_header": "Broadcast",
        "tg_bc_warn": "Warning: Frequent broadcasts may lead to account bans.",
        "tg_bc_mode": "Load Mode",
        "tg_bc_mode_whitelist": "Whitelist Only",
        "tg_bc_mode_non_whitelist": "Non-Whitelist Only",
        "tg_bc_mode_all": "All Groups",
        "tg_bc_load_btn": "Load Groups",
        "tg_bc_select_all": "Select All",
        "tg_bc_select_none": "Select None",
        "tg_bc_select_invert": "Invert Selection",
        "tg_bc_select_label": "Select Groups",
        "tg_bc_interval": "Interval (s)",
        "tg_bc_msg_placeholder": "Enter message...",
        "tg_bc_send_btn": "Start Broadcast",
        "tg_bc_records": "Broadcast Records",
        "tg_bc_clear": "Clear Records",
        "tg_broadcast_input_label": "Broadcast Message",
        "tg_bc_tip_load": "Please click Load Groups",

        "tg_log_header": "Runtime Logs",
        "tg_log_sys": "System Log",
        "tg_log_priv": "Private Log",
        "tg_log_grp": "Group Log",
        "tg_log_audit": "Audit Log",
        "tg_log_load": "Load Log",
        "tg_log_refresh": "Refresh",
        "tg_log_clear": "Clear Log",

        "tg_flow_header": "Customer to AI Flow",
        "tg_btn_start": "Start Bot",
        "tg_btn_stop": "Stop Bot",
        "tg_btn_restart": "Restart Bot",
        "tg_restart_success": "Bot Restarted",
        "tg_login_header": "Telegram Login",
        "tg_login_success": "Logged In",
        "tg_login_warning": "Not Logged In",
        "tg_login_btn": "Login to Telegram",
        "tg_config_success": "Configured",
        "tg_config_missing": "Not Configured",
        "tg_panel_header": "Telegram AI Bot Control Panel",
        "tg_broadcast_subtitle": "Send message to all active users",
        "tg_broadcast_success": "Simulated send: {}",
        "tg_logs_subtitle": "Showing last 50 records",
        "tg_stats_title": "Statistics",
        "tg_stats_total_users": "Total Users",
        "tg_stats_active_today": "Active Today",
        "tg_stats_total_msgs": "Total Messages",
        "tg_stats_trend_7d": "7-Day Trend",
        "tg_flow_subtitle": "System Message Processing Flow",
        "tg_flow_entry": "**Entry**: User sends message on Telegram → Telethon captures NewMessage → main.py handles it",
        "tg_flow_trigger": "**Trigger Check**: Private Chat / Mentioned / Keywords / Context / Group Whitelist",
        "tg_flow_branch_a": "**Branch A: QA Hit**",
        "tg_flow_branch_a_1": "- Parse qa.txt for fixed answer",
        "tg_flow_branch_a_2": "- Reply directly to Telegram",
        "tg_flow_branch_a_3": "- Write logs and update stats",
        "tg_flow_branch_b": "**Branch B: QA Miss**",
        "tg_flow_branch_b_1": "- Retrieve KB Top-2 as context",
        "tg_flow_branch_b_2": "- Call AI to generate draft",
        "tg_flow_branch_b_3": "- Keyword Pre-check: Allow-list priority; Block/Sensitive → Fallback",
        "tg_flow_branch_b_4": "- Auditor AI (Double-check): Local/Remote, returns PASS/FAIL & suggestions",
        "tg_flow_branch_b_5": "- FAIL retries up to limit, then fallback; PASS sends AI reply",
        "tg_flow_branch_b_6": "- Write audit & system logs, update stats",
        "tg_flow_kw_prio": "**Keyword Priority**",
        "tg_flow_kw_prio_1": "- allow: Direct approval",
        "tg_flow_kw_prio_2": "- block: Direct rejection, triggers fallback",
        "tg_flow_kw_prio_3": "- sensitive: Log & reject (configurable as warning)",
        "tg_flow_fallback": "**Fallback Response**",
        "tg_flow_fallback_1": "- Source: platforms/telegram/audit_fallback.txt",
        "tg_flow_fallback_2": "- Editable in Config page",
        "tg_flow_files": "**Files & Modules**",
        "tg_flow_files_1": "- Main Flow: [main.py](file:///d:/AI%20Talk/main.py)",
        "tg_flow_files_2": "- Audit & Fallback: [audit_manager.py](file:///d:/AI%20Talk/audit_manager.py)",
        "tg_flow_files_3": "- Keywords: [keyword_manager.py](file:///d:/AI%20Talk/keyword_manager.py)",
        "tg_flow_files_4": "- Admin Panel: [admin_multi.py](file:///d:/AI%20Talk/admin_multi.py)",
        "tg_bc_no_cache": "No group cache found. Run bot first.",
        "tg_bc_err_no_group": "Please select at least one group.",
        "tg_bc_err_no_content": "Please enter message content.",
        "tg_bc_fail_prefix": "❌ Broadcast Failed: {}",
        "tg_bc_success_fmt": "✅ Broadcast Done! Success: {}, Failed: {}",
        "tg_bc_no_records": "No broadcast records.",
        "tg_log_cleared": "Cleared",
        "tg_log_clear_fail": "Clear failed: {}",
        "tg_log_tip_load": "Click 'Load Log' to view content.",
        "wa_header": "WhatsApp Auto-reply Bot",
        "wa_qr_title": "WhatsApp Login QR",
        "wa_qr_scan_hint": "Please scan the QR code below with WhatsApp mobile app",
        "wa_qr_caption": "Scan to Login",
        "wa_qr_step1": "Tip: Open WhatsApp > Settings > Linked Devices > Link a Device",
        "wa_qr_step2": "⏳ QR expires in ~20s. Restart bot if expired.",
        "wa_qr_refresh": "🔄 Refresh Status",
        "wa_status_read_err": "Failed to read login status: {}",
        "wa_btn_start": "🚀 Start Bot",
        "wa_btn_stop": "⛔ Stop Bot",
        "wa_btn_restart": "🔄 Restart Bot",
        "wa_restart_success": "Bot Restarted",
        "wa_log_header": "📜 Runtime Logs",
        "wa_log_refresh": "🔄 Refresh Logs",
        "wa_log_empty": "📝 Log is empty, waiting for bot output...",
        "wa_log_missing": "⚠️ Log file not found. Please start the bot first.",
        "wa_log_clear": "🗑️ Clear Logs",
        "wa_log_cleared": "✅ Logs cleared",
        "wa_stats_header": "📊 Statistics",
        "wa_stats_reset": "🗑️ Reset Stats",
        "wa_stats_reset_success": "✅ Stats reset",
        "wa_cfg_header": "⚙️ Configuration",
        "wa_cfg_persona": "AI Persona",
        "wa_cfg_prompt_label": "Edit Prompt",
        "wa_cfg_save_prompt": "💾 Save Persona",
        "wa_cfg_keywords": "Trigger Keywords",
        "wa_cfg_keywords_label": "Group Keywords (One per line)",
        "wa_cfg_save_keywords": "💾 Save Keywords",
        "wa_cfg_switches": "Feature Switches",
        "wa_cfg_private_reply": "Private Reply",
        "wa_cfg_group_reply": "Group Reply",
        "wa_cfg_save_config": "💾 Save Switches",
        "wa_cfg_tip_restart": "💡 Changes take effect immediately, no restart needed",
        "wa_log_file_size": "📁 File size: {} bytes",
        "wa_log_last_updated": "📅 Last updated: {}",
        "wa_log_read_err": "❌ Failed to read log: {}",
        "wa_log_clear_fail": "❌ Clear failed",
        "wa_stats_total_msgs": "Total Messages",
        "wa_stats_total_replies": "Total Replies",
        "wa_stats_success_rate": "Success Rate",
        "wa_stats_failures": "Failures",
        "wa_stats_private": "Private Msgs",
        "wa_stats_group": "Group Msgs",
        "wa_stats_runtime": "⏱️ Uptime: {d}d {h}h {m}m",
        "wa_stats_last_active": "Last Active: {}",
        "wa_stats_read_err": "Failed to read stats: {}",
        "wa_stats_wait": "💡 Stats will be generated after bot runs",
        "orch_header": "Orchestrator",
        "orch_tab_stage": "Stage",
        "orch_tab_persona": "Persona",
        "orch_tab_binding": "Binding",
        "orch_stage_name": "Stage Name",
        "orch_stage_version": "Version",
        "orch_stage_content": "Content (JSON)",
        "orch_btn_save_stage": "Save Stage",
        "orch_persona_name": "Persona Name",
        "orch_persona_version": "Version",
        "orch_persona_content": "Content (JSON)",
        "orch_btn_save_persona": "Save Persona",
        "orch_binding_content": "Stage×Persona→AgentProfile (JSON)",
        "orch_btn_save_binding": "Save Binding",
        "orch_save_success": "✅ Saved",
        "sup_header": "Supervisor Monitor",
        "sup_list_title": "Active Sessions",
        "sup_select_user": "Select Session",
        "sup_force_stage": "Force Stage",
        "sup_force_persona": "Force Persona",
        "sup_handoff": "Human Handoff",
        "sup_btn_apply": "Apply",
        "sup_apply_success": "✅ Applied",
        "sup_route_title": "Recent Routing Decisions",
        "sup_route_col_user": "User",
        "sup_route_col_platform": "Platform",
        "sup_route_col_time": "Time",
        "sup_route_col_decision": "Decision",
        "audit_db_err": "Failed to load logs from DB: {}",
        "audit_save_err": "Error saving config: {}",
        "wa_start_success": "✅ WhatsApp bot started (PID: {})",
        "wa_start_fail": "❌ Start failed: {}",
        "wa_err_no_node": "❌ Node.js not detected. Please install first.",
        "wa_err_missing_deps": "❌ Dependencies missing. Run install.bat/sh first.",
        "wa_stop_success": "✅ WhatsApp bot stopped",
        "wa_stop_not_running": "⚠️ Bot is not running",
        "wa_stop_fail": "❌ Stop failed: {}",

        "acc_save_success": "✅ Account saved",
        "acc_list_title": "Account List",
        "ai_subtitle": "Visual config for AI providers, models & A/B testing",
        "ai_provider": "Provider",
        "ai_base_url": "Base URL",
        "ai_model": "Model Version",
        "ai_weight": "A/B Weight",
        "ai_api_key": "API Key (Masked)",
        "ai_timeout": "Timeout (s)",
        "tg_bc_logs_label": "Logs",
        "tg_bc_exec_err": "Execution error: {}",
        "common_coming_soon": "{} - Coming Soon",
        "common_in_dev": "### 🚧 Under Development",
        "common_planned_features": "**Planned Features:**",
        "common_contact_dev": "💡 Contact developer if you need this platform urgently.",
        "common_dev_progress": "### 📈 Development Progress",
        "common_progress_fmt": "Progress: {}%",
        
        "audit_header": "🛡️ Auditor Config Center",
        "audit_role_warn": "Access restricted to Auditors. Please switch role to Auditor in sidebar.",
        "audit_tab_keywords": "Keyword Management",
        "audit_tab_logs": "Audit Logs",
        "audit_tab_config": "Settings",
        "audit_cfg_enable": "Enable Audit System",
        "audit_cfg_remote": "Use Remote Audit Service",
        "audit_cfg_url": "Remote Server URLs",
        "audit_cfg_remote_help": "Comma separated URLs, first one prioritized",
        "audit_cfg_save": "Save Config",
        "audit_log_col_time": "Time",
        "audit_log_col_role": "Role",
        "audit_log_col_action": "Action",
        "audit_log_col_details": "Details",
        "audit_log_no_data": "No logs found",
        "audit_kw_info": "Keywords configured here take effect immediately for blocking/flagging.",
        "audit_block_header": "#### 🚫 Blocked Keywords",
        "audit_block_caption": "Triggering these will block reply immediately",
        "audit_block_count": "Total {} blocked keywords",
        "audit_block_add": "Add Blocked Keyword",
        "audit_block_add_btn": "Add",
        "audit_block_del_sel": "Select to delete",
        "audit_block_del_btn": "Delete Selected",
        "audit_block_rename_sel": "Select to rename",
        "audit_block_rename_new": "New Name",
        "audit_block_rename_btn": "Rename",
        "audit_sens_header": "#### ⚠️ Sensitive Keywords",
        "audit_sens_caption": "Triggering these will log and reject (or warn)",
        "audit_sens_count": "Total {} sensitive keywords",
        "audit_sens_add": "Add Sensitive Keyword",
        "audit_sens_del_sel": "Select to delete",
        "audit_sens_rename_sel": "Select to rename",
        "audit_allow_header": "#### ✅ Allowed Keywords (Whitelist)",
        "audit_allow_count": "Total {} allowed keywords",
        "audit_allow_add": "Add Allowed Keyword",
        "audit_allow_del_sel": "Select to delete",
        "audit_allow_rename_sel": "Select to rename",
        "audit_log_recent": "Recent Audit Logs",
        "audit_log_refresh": "Refresh Logs",
        
        "api_header": "API Gateway Management",
        "api_route_path": "Route Path /audit /reply",
        "api_route_method": "Method",
        "api_route_auth": "Auth",
        "api_route_rate": "Rate Limit req/min",
        "api_btn_add": "Add/Update Route",
        "api_save_success": "✅ Route Saved",
        "api_list_header": "Route List",

        "sys_header": "System Configuration Automation",
        "sys_env_header": "Environment Config (.env)",
        "sys_status": "Status",
        "sys_status_gen": "Generated",
        "sys_status_not_gen": "Not Generated",
        "sys_file_path": "File: {}",
        "sys_btn_gen_env": "Generate/Update .env",
        "sys_success_env": "✅ .env Generated/Updated",
        "sys_session_header": "Session File Generation",
        "sys_btn_init_session": "Silent Init Session Files",
        "sys_success_session": "✅ Session Files Initialized",
        "sys_secret_header": "Secrets Encryption & View",
        "sys_secret_caption": "Masked by default; 2FA required to view.",
        "sys_btn_gen_code": "Generate 2FA Code",
        "sys_code_info": "Generated. Enter code to view.",
        "sys_input_code": "Enter 2FA Code",
        "sys_btn_view": "View Plaintext",
        "sys_success_view": "✅ Verified (Session Valid)",
        "sys_err_code": "Invalid Code",

        "acc_header": "Account Management",
        "acc_tenant": "Current Tenant: {}",
        "acc_subtitle": "Centralized account entry, grouping, and tagging",
        "acc_col_platform": "Platform",
        "acc_col_username": "Username/ID",
        "acc_col_group": "Group",
        "acc_col_tags": "Tags (comma separated)",
        "acc_col_refresh": "Refresh Interval (min)",
        "acc_btn_add": "Add/Update Account",
        
        "cs_title": "🚧 Platform Under Development",
        "cs_desc": "**{}** is under development, stay tuned!",
        "cs_plan_title": "**Planned Features:**",
        "cs_plan_1": "✅ Auto Reply",
        "cs_plan_2": "✅ Context Memory",
        "cs_plan_3": "✅ Broadcast",
        "cs_plan_4": "✅ Web Management",
        "cs_plan_5": "✅ Stats & Reports",
        "cs_eta": "**ETA:** TBD",
        "cs_contact": "💡 Contact developer if you need this urgently.",
        "cs_progress_title": "### 📈 Progress",
        "cs_progress_caption": "Completion: {}%",

        "wa_status_running": "🟢 Running",
        "wa_status_stopped": "🔴 Stopped",
    }
}

PLATFORMS = {
    'ai_learning': {
        'name': 'AI学习中心',
        'icon': '🧪',
        'color': '#7c3aed',
        'status': 'available',
        'description': '对话数据清洗与可学习集管理',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'skills': {
        'name': '技能中心',
        'icon': '🧩',
        'color': '#2563eb',
        'status': 'available',
        'description': '技能配置与绑定业务线',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'knowledge': {
        'name': '📚',
        'icon': '📚',
        'color': '#8b5cf6',
        'status': 'available',
        'description': '知识库配置与检索',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'audit': {
        'name': '🛡️',
        'icon': '🛡️',
        'color': '#FF5733',
        'status': 'available',
        'description': '关键词与日志管理',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'business': {
        'name': '商业化运营',
        'icon': '📊',
        'color': '#F59E0B',
        'status': 'available',
        'description': '订阅/计费/数据看板',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'telegram': {
        'name': 'Telegram',
        'icon': '📱',
        'color': '#0088cc',
        'status': 'available',  # available, unavailable, coming_soon
        'description': '全功能支持 - 私聊/群聊/频道',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'whatsapp': {
        'name': 'WhatsApp',
        'icon': '💬',
        'color': '#25D366',
        'status': 'available',
        'description': '✅ 可用 - 私聊/群聊自动回复',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'accounts': {
        'name': '账号管理',
        'icon': '👥',
        'color': '#4b5563',
        'status': 'available',
        'description': '集中录入与分组/标签管理',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'ai_config': {
        'name': 'AGNT AI配置中心',
        'icon': '🧠',
        'color': '#0ea5e9',
        'status': 'available',
        'description': 'AI服务商接入与A/B测试',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'api_gateway': {
        'name': 'API接口管理中心',
        'icon': '🛣️',
        'color': '#16a34a',
        'status': 'available',
        'description': '统一网关/权限/流控/日志',
        'roles': ['SuperAdmin']
    },
    'sys_config': {
        'name': '系统配置自动化',
        'icon': '🧩',
        'color': '#0f766e',
        'status': 'available',
        'description': '环境/会话/密钥自动化',
        'roles': ['SuperAdmin']
    },
    'system_admin': {
        'name': '系统管理',
        'icon': '🛠️',
        'color': '#111827',
        'status': 'available',
        'description': '系统账号/IP白名单/登录日志/升级',
        'roles': ['SuperAdmin']
    },

    'twitter': {
        'name': 'Twitter/X',
        'icon': '🐦',
        'color': '#1DA1F2',
        'status': 'coming_soon',
        'description': '规划中 - DM + 提及回复',
        'roles': ['SuperAdmin']
    },
    'facebook': {
        'name': 'Facebook',
        'icon': '📘',
        'color': '#1877F2',
        'status': 'coming_soon',
        'description': '规划中 - Page/Group',
        'roles': ['SuperAdmin']
    },
    'messenger': {
        'name': 'Messenger',
        'icon': '💬',
        'color': '#00B2FF',
        'status': 'coming_soon',
        'description': '规划中 - Auto Reply',
        'roles': ['SuperAdmin']
    },
    'wechat': {
        'name': 'WeChat',
        'icon': '🟢',
        'color': '#07C160',
        'status': 'coming_soon',
        'description': '规划中 - 公众号/企业微信',
        'roles': ['SuperAdmin']
    },
    'instagram': {
        'name': 'Instagram',
        'icon': '📸',
        'color': '#E1306C',
        'status': 'coming_soon',
        'description': '规划中 - DM',
        'roles': ['SuperAdmin']
    },
    'discord': {
        'name': 'Discord',
        'icon': '💜',
        'color': '#5865F2',
        'status': 'coming_soon',
        'description': '规划中 - 服务器 Bot'
    },
    'orchestrator': {
        'name': 'AI剧本配置',
        'icon': '🎼',
        'color': '#3b82f6',
        'status': 'available',
        'description': '流程/人设/绑定与评估',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'supervisor': {
        'name': '主管决策',
        'icon': '👀',
        'color': '#22c55e',
        'status': 'available',
        'description': '会话与决策记录',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'help_center': {
        'name': '帮助中心',
        'icon': '🆘',
        'color': '#ef4444',
        'status': 'available',
        'description': '文档与使用指南',
        'roles': ['SuperAdmin', 'BusinessAdmin']
    },
    'system_status': {
        'name': '系统状态',
        'icon': '📈',
        'color': '#10b981',
        'status': 'available',
        'description': '系统运行健康度看板',
        'roles': ['SuperAdmin']
    },
    'test_cases': {
        'name': '测试用例集',
        'icon': '🧪',
        'color': '#f97316',
        'status': 'available',
        'description': '回归测试用例与一键执行',
        'roles': ['SuperAdmin']
    }
}

